services:
  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/krakend
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    environment:
      - KRAKEND_CONFIG=/etc/krakend/krakend.json
    networks:
      - backend