###
http://localhost:3001/users

###
http://localhost:3001/users/1

###
http://localhost:3001/users/9999

###
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "
}